# Generated by Django 4.1.2 on 2022-12-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_publish',
        ),
    ]
